rspec: fix vm_definition and driver cases
- image_mode default
- add add_name() for test sequence.
it fixes following error
VagrantPlugins::ProviderKvm::Driver::Driver#import does not raise exception
Failure/Error: expect do
expected no Exception, got #<Libvirt::DefinitionError: Call to virDomainDefineXML failed: missing name information> with backtrace:
- fix following:
VagrantPlugins::ProviderKvm::Driver::Driver#import does not raise exception
Failure/Error: expect do
expected no Exception, got #<NoMethodError: undefined method `create_volume_xml' for nil:NilClass> with backtrace:
/home/travis/build/miurahr/vagrant-kvm/lib/vagrant-kvm/driver/driver.rb:96:in `create_volume'

Signed-off-by: Hiroshi Miura <miurahr@linux.com>